import { motion } from "motion/react";

const PALETTE = { a: "#ffffff", b: "#c9c9d1", c: "#6b6b76", bg: "#050505" } as const;

export default function Numbers() {
  const stats = [
    { value: "240M+", label: "Views generated by EX-Media" },
    { value: "24K+", label: "Learners on EX-Edu platform" },
    { value: "18M+", label: "Messages/mo via EX-Bot" },
    { value: "99.98%", label: "Uptime across all platforms" },
  ];

  return (
    <section
      data-palette=""
      data-palette-a={PALETTE.a}
      data-palette-b={PALETTE.b}
      data-palette-c={PALETTE.c}
      data-palette-bg={PALETTE.bg}
      className="relative py-20 md:py-28 border-t border-white/[0.06] overflow-hidden"
    >
      <div className="absolute inset-0 aurora" />
      <div className="relative w-[min(1200px,94vw)] mx-auto">
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-px bg-white/[0.06] rounded-3xl overflow-hidden">
          {stats.map(({ value, label }, i) => (
            <motion.div
              key={label}
              initial={{ opacity: 0, scale: 0.95 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true, amount: 0.4 }}
              transition={{ duration: 0.7, delay: i * 0.1 }}
              className="bg-[#050505] flex flex-col gap-2 p-8 md:p-10"
            >
              <span className="font-display text-4xl md:text-5xl text-white">{value}</span>
              <span className="text-xs text-white/40 leading-relaxed">{label}</span>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
